### ISSUE TITLE
Can't you simply get CPU load?

### ISSUE THREAD

**Issue by lihas** [dpw/whichcpus#1]
When you determine which CPUs are available, it must be to run a program on them. Why not get the current CPU load, and run the program on the CPU with least load?

**Comment by dpw** [comment]
This program is intended to test which CPUs are available to it, in order to probe Linux's various CPU selection mechanisms.  It should find all the CPUs available.  If as you suggest, it just ran on the CPU with the least load, that would only tell about one available CPU.  Also, in order to "run on the CPU with the least load", it would have to use one of Linux's CPU selection mechanisms, which would interfere with demonstrating how they work and interact.
